version: '3.9'

services:
  backend:
    container_name: kpd-back-container
    build: ./backend
    image: kpd-back-image
    networks:
      - backend
    ports:
      - 4000:3000
    env_file:
      - backend/.env
    depends_on:
      - database
    restart: on-failure 

  frontend:
    container_name: kpd-front-container
    build: ./frontend
    image: kpd-front-image
    networks:
      - frontend
    ports:
      - 8081:80
    restart: on-failure 

  database:
    container_name: database
    image: postgres
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - backend/.env
    restart: on-failure 

networks:
  backend:
  frontend:

volumes:
  postgres_data: 
