version: '3.9'

services:
  backend:
    container_name: compose-back-container
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-back-image
    networks:
      - backend
    ports:
      - 4000:3000
    env_file:
      - backend/.env
    depends_on:
      - postgres

  frontend:
    container_name: compose-front-container
    build:
      context: frontend
      dockerfile: Dockerfile
    image: compose-front-image
    networks:
      - frontend
    ports:
      - 8081:80

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - backend/.env

networks:
  backend:
  frontend:

volumes:
  postgres_data: 
